### ISSUE TITLE
Use yargs or similar

### ISSUE THREAD

**Issue by lazarljubenovic** [weareneopix/daily-log#6]
If we're gonna keep adding features here, that means more command line arguments. So we should switch to using a library that handles that in a nice way.

An example of such library is [yargs](http://yargs.js.org/), but we are by no means bound to use that exact one. Feel free to explore around. We need a simple and elegant solution, no need for something which is intended for huge apps.

**Comment by ilicmarko** [comment]
There are two other options for parsing arguments, they are a lot lighter and provide more CLI options:
* [CommanderJS](https://github.com/tj/commander.js)
* [Meow](https://github.com/sindresorhus/meow)

As far as I know, all of the above and even yargs lack required arguments. This can be easily fixed with one if statement.
